name: Helm

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  issues: write
  id-token: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4
      - uses: azure/setup-helm@v4.2.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: helm repo add cert-manager https://charts.jetstack.io
      - run: helm dependency update
        working-directory: ./helm/agent
      - run: helm dependency build  
        working-directory: ./helm/agent
      - run: helm package helm/agent
      - run: helm push agent-*.tgz oci://ghcr.io/wentidev/helm